[tools]
"cargo:wasm-opt" = "latest"
node = "lts"
rust = "stable"

[tasks."check:web"]
description = "Run TypeScript type/compile checks"
dir = "{{ config_root }}/web"
depends = ["generate:spacetimedb_bindings"]
run = "npm run test:ts"

[tasks."check:spacetimedb"]
description = "Run Rust type/compile checks"
dir = "{{ config_root }}/spacetimedb"
run = "cargo clippy"

[tasks.check]
depends = ["check:web", "check:spacetimedb"]

[tasks."build:web"]
description = "Build frontend"
dir = "{{ config_root }}/web"
depends = ["generate:spacetimedb_bindings"]
run = "npm run build"

[tasks."build:spacetimedb"]
description = "Build SpacetimeDB module"
dir = "{{ config_root }}/spacetimedb"
run = "spacetime build"

[tasks."generate:spacetimedb_bindings"]
description = "Generate SpacetimeDB bindings"
run = "spacetime generate --lang ts --out-dir web/src/module_bindings --yes"

[tasks.build]
description = "Build SpacetimeDB module and frontend"
depends = ["build:spacetimedb", "build:web"]

[tasks."publish:spacetimedb"]
description = "Publish SpacetimeDB module"
run = [
    "spacetime logout",
    'spacetime login --token "${SPACETIME_TOKEN}"',
    "spacetime publish --yes"
]

[tasks."dev:web"]
description = "Start frontend development server"
dir = "{{ config_root }}/web"
run = "npm run dev"

[tasks."dev:spacetimedb"]
description = "Start SpacetimeDB development server"
run = "spacetime dev --yes"

[tasks."dev"]
description = "Start development server"
depends = ["dev:web", "dev:spacetimedb"]
