// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Book = __t.object("Book", {
  id: __t.u64(),
  title: __t.string(),
  author: __t.string(),
  carretPosition: __t.u32(),
  startedAt: __t.timestamp(),
});
export type Book = __Infer<typeof Book>;

export const BookWord = __t.object("BookWord", {
  id: __t.u64(),
  bookId: __t.u64(),
  decidedAt: __t.timestamp(),
  get voteDistribution() {
    return __t.array(BookWordVotes);
  },
});
export type BookWord = __Infer<typeof BookWord>;

export const BookWordCandidate = __t.object("BookWordCandidate", {
  id: __t.u64(),
  bookId: __t.u64(),
  word: __t.string(),
  position: __t.u32(),
});
export type BookWordCandidate = __Infer<typeof BookWordCandidate>;

export const BookWordView = __t.object("BookWordView", {
  word: __t.string(),
  decidedAt: __t.timestamp(),
  get votesDistribution() {
    return __t.array(BookWordVotesView);
  },
});
export type BookWordView = __Infer<typeof BookWordView>;

export const BookWordVote = __t.object("BookWordVote", {
  id: __t.u64(),
  candidateId: __t.u64(),
  voter: __t.identity(),
  get location() {
    return Iso3166Alpha2;
  },
});
export type BookWordVote = __Infer<typeof BookWordVote>;

export const BookWordVotes = __t.object("BookWordVotes", {
  candidateId: __t.u64(),
  voteCount: __t.u32(),
});
export type BookWordVotes = __Infer<typeof BookWordVotes>;

export const BookWordVotesView = __t.object("BookWordVotesView", {
  word: __t.string(),
  voteCount: __t.u32(),
});
export type BookWordVotesView = __Infer<typeof BookWordVotesView>;

export const BookWordVotingEnds = __t.object("BookWordVotingEnds", {
  id: __t.u64(),
  bookId: __t.u64(),
  position: __t.u32(),
  scheduledAt: __t.scheduleAt(),
});
export type BookWordVotingEnds = __Infer<typeof BookWordVotingEnds>;

export const CurrentBookView = __t.object("CurrentBookView", {
  carretPosition: __t.u32(),
  get words() {
    return __t.array(BookWordView);
  },
});
export type CurrentBookView = __Infer<typeof CurrentBookView>;

export const CurrentCandidateView = __t.object("CurrentCandidateView", {
  word: __t.string(),
  votesAmount: __t.u32(),
});
export type CurrentCandidateView = __Infer<typeof CurrentCandidateView>;

export const CurrentVotingView = __t.object("CurrentVotingView", {
  votingEnds: __t.timestamp(),
  get candidates() {
    return __t.array(CurrentCandidateView);
  },
});
export type CurrentVotingView = __Infer<typeof CurrentVotingView>;

// The tagged union or sum type for the algebraic type `Iso3166Alpha2`.
export const Iso3166Alpha2 = __t.enum("Iso3166Alpha2", {
  Af: __t.unit(),
  Al: __t.unit(),
  Dz: __t.unit(),
  Ad: __t.unit(),
  Ao: __t.unit(),
  Ag: __t.unit(),
  Ar: __t.unit(),
  Am: __t.unit(),
  Au: __t.unit(),
  At: __t.unit(),
  Az: __t.unit(),
  Bs: __t.unit(),
  Bh: __t.unit(),
  Bd: __t.unit(),
  Bb: __t.unit(),
  By: __t.unit(),
  Be: __t.unit(),
  Bz: __t.unit(),
  Bj: __t.unit(),
  Bt: __t.unit(),
  Bo: __t.unit(),
  Ba: __t.unit(),
  Bw: __t.unit(),
  Br: __t.unit(),
  Bn: __t.unit(),
  Bg: __t.unit(),
  Bf: __t.unit(),
  Bi: __t.unit(),
  Kh: __t.unit(),
  Cm: __t.unit(),
  Ca: __t.unit(),
  Cv: __t.unit(),
  Cf: __t.unit(),
  Td: __t.unit(),
  Cl: __t.unit(),
  Cn: __t.unit(),
  Co: __t.unit(),
  Km: __t.unit(),
  Cg: __t.unit(),
  Cd: __t.unit(),
  Cr: __t.unit(),
  Hr: __t.unit(),
  Cu: __t.unit(),
  Cy: __t.unit(),
  Cz: __t.unit(),
  Dk: __t.unit(),
  Dj: __t.unit(),
  Dm: __t.unit(),
  Do: __t.unit(),
  Ec: __t.unit(),
  Eg: __t.unit(),
  Sv: __t.unit(),
  Gq: __t.unit(),
  Er: __t.unit(),
  Ee: __t.unit(),
  Sz: __t.unit(),
  Et: __t.unit(),
  Fj: __t.unit(),
  Fi: __t.unit(),
  Fr: __t.unit(),
  Ga: __t.unit(),
  Gm: __t.unit(),
  Ge: __t.unit(),
  De: __t.unit(),
  Gh: __t.unit(),
  Gr: __t.unit(),
  Gd: __t.unit(),
  Gt: __t.unit(),
  Gn: __t.unit(),
  Gw: __t.unit(),
  Gy: __t.unit(),
  Ht: __t.unit(),
  Hn: __t.unit(),
  Hu: __t.unit(),
  Is: __t.unit(),
  In: __t.unit(),
  Id: __t.unit(),
  Ir: __t.unit(),
  Iq: __t.unit(),
  Ie: __t.unit(),
  Il: __t.unit(),
  It: __t.unit(),
  Ci: __t.unit(),
  Jm: __t.unit(),
  Jp: __t.unit(),
  Jo: __t.unit(),
  Kz: __t.unit(),
  Ke: __t.unit(),
  Ki: __t.unit(),
  Xk: __t.unit(),
  Kw: __t.unit(),
  Kg: __t.unit(),
  La: __t.unit(),
  Lv: __t.unit(),
  Lb: __t.unit(),
  Ls: __t.unit(),
  Lr: __t.unit(),
  Ly: __t.unit(),
  Li: __t.unit(),
  Lt: __t.unit(),
  Lu: __t.unit(),
  Mg: __t.unit(),
  Mw: __t.unit(),
  My: __t.unit(),
  Mv: __t.unit(),
  Ml: __t.unit(),
  Mt: __t.unit(),
  Mh: __t.unit(),
  Mr: __t.unit(),
  Mu: __t.unit(),
  Mx: __t.unit(),
  Fm: __t.unit(),
  Md: __t.unit(),
  Mc: __t.unit(),
  Mn: __t.unit(),
  Me: __t.unit(),
  Ma: __t.unit(),
  Mz: __t.unit(),
  Mm: __t.unit(),
  Na: __t.unit(),
  Nr: __t.unit(),
  Np: __t.unit(),
  Nl: __t.unit(),
  Nz: __t.unit(),
  Ni: __t.unit(),
  Ne: __t.unit(),
  Ng: __t.unit(),
  Kp: __t.unit(),
  Mk: __t.unit(),
  No: __t.unit(),
  Om: __t.unit(),
  Pk: __t.unit(),
  Pw: __t.unit(),
  Ps: __t.unit(),
  Pa: __t.unit(),
  Pg: __t.unit(),
  Py: __t.unit(),
  Pe: __t.unit(),
  Ph: __t.unit(),
  Pl: __t.unit(),
  Pt: __t.unit(),
  Qa: __t.unit(),
  Ro: __t.unit(),
  Ru: __t.unit(),
  Rw: __t.unit(),
  Kn: __t.unit(),
  Lc: __t.unit(),
  Vc: __t.unit(),
  Ws: __t.unit(),
  Sm: __t.unit(),
  St: __t.unit(),
  Sa: __t.unit(),
  Sn: __t.unit(),
  Rs: __t.unit(),
  Sc: __t.unit(),
  Sl: __t.unit(),
  Sg: __t.unit(),
  Sk: __t.unit(),
  Si: __t.unit(),
  Sb: __t.unit(),
  So: __t.unit(),
  Za: __t.unit(),
  Kr: __t.unit(),
  Ss: __t.unit(),
  Es: __t.unit(),
  Lk: __t.unit(),
  Sd: __t.unit(),
  Sr: __t.unit(),
  Se: __t.unit(),
  Ch: __t.unit(),
  Sy: __t.unit(),
  Tw: __t.unit(),
  Tj: __t.unit(),
  Tz: __t.unit(),
  Th: __t.unit(),
  Tl: __t.unit(),
  Tg: __t.unit(),
  To: __t.unit(),
  Tt: __t.unit(),
  Tn: __t.unit(),
  Tr: __t.unit(),
  Tm: __t.unit(),
  Tv: __t.unit(),
  Ug: __t.unit(),
  Ua: __t.unit(),
  Ae: __t.unit(),
  Gb: __t.unit(),
  Us: __t.unit(),
  Uy: __t.unit(),
  Uz: __t.unit(),
  Vu: __t.unit(),
  Va: __t.unit(),
  Ve: __t.unit(),
  Vn: __t.unit(),
  Ye: __t.unit(),
  Zm: __t.unit(),
  Zw: __t.unit(),
});
export type Iso3166Alpha2 = __Infer<typeof Iso3166Alpha2>;

export const MyVote = __t.object("MyVote", {
  word: __t.string(),
  get location() {
    return Iso3166Alpha2;
  },
});
export type MyVote = __Infer<typeof MyVote>;

